import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { AnalyticsProvider } from './hooks/use-analytics'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AnalyticsProvider
          writeKey="sample-write-key"
          enableInAppPlugin={true}
          siteId="sample-site-id"
        >
          {children}
        </AnalyticsProvider>
      </body>
    </html>
  )
}
